# swagger.yaml
openapi: 3.0.0
info:
  title: E-Commerce API
  version: "1.0.0"
paths:
   /customers/create:
     post: 
     summary: Create a new Customer
     requestBody:
       content:
         application/json:
           schema:
             type: object
             properties:
               name:
                 type: string
               email:
                 type: string
               phone:
                 type: string
     responses:
       "201":
         description: Customer created successfully
       "400":
         description: Invalid input
          
